---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  directories:
    - node_modules
    - $HOME/.yarn
    - $HOME/.yarn-cache
    - $HOME/.cache # includes bowers cache

before_install:
  - npm config set spin false
  - npm install -g bower
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add phantomjs-prebuilt
  - yarn --version
  - bower --version
  - phantomjs --version

install:
  - yarn install
  - bower install

script:
  - yarn run test

addons:
    code_climate:
        repo_token: de4cedac171d091882efe2719ae10fbdb5e5054077123f8455b251719973a606
