url: "http://kaliber5.github.io/ember-bootstrap/" # the base hostname & protocol for your site
baseurl: "/ember-bootstrap"
title: "ember-bootstrap"

# This is used by feed.xml. Uncomment if you want to use it.
# description: "..."

gems:
  - jemoji
exclude:
  - "README.md"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "tmp/"
  - "node_modules/"
  - "bower_components/"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
